"""Unit tests for safety-signal-monitor (generated by the Coder agent)."""
from feature import safety_signal_monitor


def test_counts_flagged_records():
    records = [{"id": "A", "signal": True},
               {"id": "B", "signal": False},
               {"id": "C", "signal": True}]
    result = safety_signal_monitor(records)
    assert result["flagged"] == ["A", "C"]
    assert result["n"] == 2


def test_handles_empty():
    assert safety_signal_monitor([])["n"] == 0
